services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: shadowboard-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperStrong!Passw0rd2026
